### ISSUE TITLE
Need migration to webpack version 5

### ISSUE THREAD

**Issue by budarin** [Perlmint/script-runner-webpack-plugin#1]
Try to use in wp5

```
[webpack-cli] TypeError: ScriptRunnerPlugin is not a constructor
    at Object.<anonymous> (/Users/projects/raketa/config/webpack/dev.webpack.config.js:76:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at WebpackCLI.tryRequireThenImport (/Users/projects/raketa/node_modules/webpack-cli/lib/webpack-cli.js:244:16)
    at loadConfigByPath (/Users/projects/raketa/node_modules/webpack-cli/lib/webpack-cli.js:1712:30)
    at /Users/projects/raketa/node_modules/webpack-cli/lib/webpack-cli.js:1767:11
    ```

**Comment by Perlmint** [comment]
Thanks for reporting
I just published 1.0.0 with webpack5 support.

But, In your case, It seems like an issue not related to webpack 5. This plugin exports class as a default item of ES module. Please check your import statement.

You can import this plugin by

```javascript
const ScriptRunnerPlugin = require('script-runner-webpack-plugin').default;
```

or

```javascript
import ScriptRunnerPlugin from 'script-runner-webpack-plugin';
```
